version: "3"

services:
  weskool:
    restart: unless-stopped
    build:
      context: ./weskoolmm #Must be directory with Dockerfile
      dockerfile: Dockerfile
    environment:
      - JWT
      - CERTKEY
      - CERTCHAIN
    volumes:
      - /etc/letsencrypt/archive/weskool.team:/etc/letsencrypt/archive/weskool.team/
      - /etc/letsencrypt/live/weskool.team/:/etc/nginx/certs/
    ports:
      - 8080:80
    # links:
    #   - db
    depends_on:
      - db
      - db1
      - db2
      - api
      - mongo-replicator

  db:
    image: mongo
    # environment:
    #   MONGO_INITDB_ROOT_USERNAME: root
    #   MONGO_INITDB_ROOT_PASSWORD: password
    command: --replSet rs0 --port 27017 --bind_ip localhost --dbpath /data/db
    network_mode: "host"
    # networks:
    #   - mongo-cluster
    # ports:
    #   - 27017:27017
    volumes:
      - ~/projs/DockerWeskool/db/nodes/rdb1:/data/db

  db1:
    image: mongo
    command: --replSet rs0 --port 27018 --bind_ip localhost --dbpath /data/db
    network_mode: "host"
    # networks:
    #   - mongo-cluster
    # ports:
    #   - 27018:27017
    volumes:
      - ~/projs/DockerWeskool/db/nodes/rdb2:/data/db
    depends_on:
      - db

  db2:
    image: mongo
    command: --replSet rs0 --port 27019 --bind_ip localhost --dbpath /data/db
    network_mode: "host"
    # networks:
    #   - mongo-cluster
    # ports:
    #   - 27019:27017
    volumes:
      - ~/projs/DockerWeskool/db/nodes/rdb3:/data/db
    depends_on:
      - db1

  mongo-replicator:
    build: ./db/replicator
    network_mode: "host"
    # networks:
    #   - mongo-cluster
    depends_on:
      - db
      - db1
      - db2

  api:
    build:
      context: ./Api
      dockerfile: Dockerfile
    environment:
      - ENV
      - JWT
      - CERTKEY
      - CERTCHAIN
    network_mode: "host"
    command: ["node", "index.js"]
    volumes:
      - /etc/letsencrypt/live/weskool.team:/etc/letsencrypt/live/weskool.team/
      - /etc/letsencrypt/archive/weskool.team:/etc/letsencrypt/archive/weskool.team/
    # ports:
    #   - 5443:5443
    # links:
    #   - db
    depends_on:
      - db
      - db1
      - db2
      - mongo-replicator

  uploads:
    build:
      context: ./Api
      dockerfile: Dockerfile
    environment:
      - ENV
      - JWT
      - CERTKEY
      - CERTCHAIN
    network_mode: "host"
    volumes:
      - /etc/letsencrypt/live/weskool.team:/etc/letsencrypt/live/weskool.team/
      - /etc/letsencrypt/archive/weskool.team:/etc/letsencrypt/archive/weskool.team/
      - ~/projs/DockerWeskool/db:/db
      - ~/projs/DockerWeskool/Api/modules:/modules
    command: ["node", "uploads.js"]
    depends_on:
      - db
      - db1
      - db2
      - mongo-replicator
      - weskool

  downloads:
    build:
      context: ./Api
      dockerfile: Dockerfile
    environment:
      - ENV
      - JWT
      - CERTKEY
      - CERTCHAIN
    network_mode: "host"
    volumes:
      - /etc/letsencrypt/live/weskool.team:/etc/letsencrypt/live/weskool.team/
      - /etc/letsencrypt/archive/weskool.team:/etc/letsencrypt/archive/weskool.team/
      - ~/projs/DockerWeskool/db:/db
      - ~/projs/DockerWeskool/Api/modules:/modules
    command: ["node", "downloads.js"]
    depends_on:
      - db
      - db1
      - db2
      - mongo-replicator
      - weskool
      - uploads

networks:
  mongo-cluster:
    driver: bridge
