version: "3"

services:

  # Mongo DB server
  mongodb:
    container_name: mongo-weskool
    restart: unless-stopped
    image: mongo
    network_mode: "host"
    environment:
      - MONGO_INITDB_ROOT_USERNAME
      - MONGO_INITDB_ROOT_PASSWORD
    volumes:
      - ~/projs/weskool/db/nodes/rdb1:/data/db
  
  weskool:
    restart: unless-stopped
    build:
      context: ./frontend #Must be directory with Dockerfile
      dockerfile: Dockerfile
    environment:
      - ENV
      - JWT
      - CERTKEY
      - CERTCHAIN
    volumes:
      - /etc/letsencrypt:/etc/nginx/certs/
    ports:
      - 80:80
      - 443:443
    # links:
    #   - db
    depends_on:
      - mongodb
      - api

  api:
    restart: unless-stopped
    build:
      context: ./api
      dockerfile: Dockerfile
    environment:
      - ENV
      - JWT
      - CERTKEY
      - CERTCHAIN
      - USER_NAME
      - PASSWORD
      - USER_EMAIL
      - PROJECT_NAME
      - MONGO_INITDB_ROOT_USERNAME
      - MONGO_INITDB_ROOT_PASSWORD
    network_mode: "host"
    command: ["node", "index.js"]
    volumes:
      - /etc/letsencrypt/live/weskool.team:/etc/letsencrypt/live/weskool.team/
      - /etc/letsencrypt/archive/weskool.team:/etc/letsencrypt/archive/weskool.team/
    # ports:
    #   - 5443:5443
    # links:
    #   - db
    depends_on:
      - mongodb

  uploads:
    restart: unless-stopped
    build:
      context: ./api
      dockerfile: Dockerfile
    environment:
      - ENV
      - JWT
      - CERTKEY
      - CERTCHAIN
    network_mode: "host"
    volumes:
      - /etc/letsencrypt/live/weskool.team:/etc/letsencrypt/live/weskool.team/
      - /etc/letsencrypt/archive/weskool.team:/etc/letsencrypt/archive/weskool.team/
      - ~/projs/weskool/db/uploads:/db/uploads/
    command: ["node", "uploads.js"]
    depends_on:
      - mongodb

  downloads:
    restart: unless-stopped
    build:
      context: ./api
      dockerfile: Dockerfile
    environment:
      - ENV
      - JWT
      - CERTKEY
      - CERTCHAIN
    network_mode: "host"
    volumes:
      - /etc/letsencrypt/live/weskool.team:/etc/letsencrypt/live/weskool.team/
      - /etc/letsencrypt/archive/weskool.team:/etc/letsencrypt/archive/weskool.team/
      - ~/projs/weskool/db:/db
      - ~/projs/weskool/api/modules:/modules
    command: ["node", "downloads.js"]
    depends_on:
      - mongodb

  